-- Seeds each standard OLL algorithm plus its first four listed alternatives from oll-algs.pdf.
-- Run this after AlgorithmSeeder has created the OLL groups and numbered cases.

BEGIN;

WITH oll_algorithms(case_number, moves) AS (
    VALUES
        (1, '(R U2 R'') (R'' F R F'') U2 (R'' F R F'')'),
        (1, 'R U2 R2 F R F'' U2 R'' F R F'''),
        (1, 'y R U'' R2 D'' r U'' r'' D R2 U R'''),
        (1, 'f R U R'' U'' R f'' U'' r'' U'' R U M'''),
        (1, 'L'' U2 L2 F'' L'' F U2 L F'' L'' F'),
        (2, 'F (R U R'' U'') F'' f (R U R'' U'') f'''),
        (2, 'y'' R U'' R2 D'' r U r'' D R2 U R'''),
        (2, 'F R U R'' U'' S R U R'' U'' f'''),
        (2, 'F R U R'' U'' F'' f R U R'' U'' f'''),
        (2, 'y r U r'' U2 R U2 R'' U2 r U'' r'''),
        (3, 'y'' f (R U R'' U'') f'' (U'') F (R U R'' U'') F'''),
        (3, 'y'' f R U R'' U'' f'' U'' F R U R'' U'' F'''),
        (3, 'y R'' F2 R2 U2 R'' F R U2 R2 F2 R'),
        (3, 'r'' R2 U R'' U r U2 r'' U M'''),
        (3, 'M R U R'' U r U2 r'' U M'''),
        (4, 'y'' f (R U R'' U'') f'' (U) F (R U R'' U'') F'''),
        (4, 'y'' R'' F2 R2 U2 R'' F'' R U2 R2 F2 R'),
        (4, 'y'' f R U R'' U'' f'' U F R U R'' U'' F'''),
        (4, 'R'' F R F'' U'' S R'' U'' R U R S'''),
        (4, 'y F U R U'' R'' F'' U'' F R U R'' U'' F'''),
        (5, 'r'' U2 (R U R'' U) r'),
        (5, 'r'' U2 R U R'' U r'),
        (5, 'y2 l'' U2 L U L'' U l'),
        (5, 'y2 R'' F2 r U r'' F R'),
        (5, 'y2 R'' F2 L F L'' F R'),
        (6, 'r U2 (R'' U'' R U'') r'''),
        (6, 'r U2 R'' U'' R U'' r'''),
        (6, 'F U'' R2 D R'' U'' R D'' R2 U F'''),
        (6, 'y2 l U2 L'' U'' L U'' l'''),
        (6, 'L F2 l'' U'' l F'' L'''),
        (7, 'r (U R'' U R) U2 r'''),
        (7, 'r U R'' U R U2 r'''),
        (7, 'S'' R U R'' U R U2 R'' U S'),
        (7, 'L'' U2 L U2 L F'' L'' F'),
        (7, 'y2 f R U R'' U'' f'' y2 F R'' F'' r U R U'' r'''),
        (8, 'y2 r'' (U'' R U'' R'') U2 r'),
        (8, 'y2 r'' U'' R U'' R'' U2 r'),
        (8, 'l'' U'' L U'' L'' U2 l'),
        (8, 'R U2 R'' U2 R'' F R F'''),
        (8, 'R'' F'' r U'' r'' F2 R'),
        (9, 'y (R U R'' U'') (R'' F R) (R U R'' U'') F'''),
        (9, 'y R U R'' U'' R'' F R2 U R'' U'' F'''),
        (9, 'R U2 R'' U'' S'' R U'' R'' S'),
        (9, 'y2 F'' U'' F r U'' r'' U r U r'''),
        (9, 'y'' L'' U'' L U'' L F'' L'' F L'' U2 L'),
        (10, '(R U R'' U) (R'' F R F'') (R U2 R'')'),
        (10, 'R U R'' U R'' F R F'' R U2 R'''),
        (10, 'y F U F'' R'' F R U'' R'' F'' R'),
        (10, 'y M'' R'' U2 R U R'' U R U M'),
        (10, 'y2 L'' U'' L U L F'' L2 U'' L U F'),
        (11, 'M (R U R'' U R U2 R'') U M'''),
        (11, 'r'' R2 U R'' U R U2 R'' U M'''),
        (11, 'y2 r U R'' U R'' F R F'' R U2 r'''),
        (11, 'S R U R'' U R U2 R'' U2 S'''),
        (11, 'M R U R'' U R U2 R'' U M'''),
        (12, 'y'' M'' (R'' U'' R U'' R'' U2 R) U'' M'),
        (12, 'y'' M'' R'' U'' R U'' R'' U2 R U'' M'),
        (12, 'F R U R'' U'' F'' U F R U R'' U'' F'''),
        (12, 'y'' S R'' U'' R U'' R'' U2 R U2 S'''),
        (12, 'y M L'' U'' L U'' L'' U2 L U'' M'''),
        (13, '(r U'' r'') U'' (r U r'') (F'' U F)'),
        (13, 'F U R U2 R'' U'' R U R'' F'''),
        (13, 'F U R U'' R2 F'' R U R U'' R'''),
        (13, 'r U'' r'' U'' r U r'' F'' U F'),
        (13, 'y2 f R U R2 U'' R'' U R U'' f'''),
        (14, 'R'' F (R U R'') F'' R (F U'' F'')'),
        (14, 'R'' F R U R'' F'' R F U'' F'''),
        (14, 'r U R'' U'' r'' F R2 U R'' U'' F'''),
        (14, 'l'' U l U l'' U'' l F U'' F'''),
        (14, 'S R U R'' U'' R'' F R2 U R'' U'' f'''),
        (15, '(r'' U'' r) (R'' U'' R U) (r'' U r)'),
        (15, 'r'' U'' r R'' U'' R U r'' U r'),
        (15, 'y2 l'' U'' l L'' U'' L U l'' U l'),
        (15, 'r'' U'' M'' U'' R U r'' U r'),
        (15, 'y2 R'' F'' R L'' U'' L U R'' F R'),
        (16, '(r U r'') (R U R'' U'') (r U'' r'')'),
        (16, 'r U r'' R U R'' U'' r U'' r'''),
        (16, 'r U M U R'' U'' r U'' r'''),
        (16, 'y2 R'' F R U R'' U'' F'' R U'' R'' U2 R'),
        (16, 'y2 l U l'' L U L'' U'' l U'' l'''),
        (17, '(R U R'' U) (R'' F R F'') U2 (R'' F R F'')'),
        (17, 'R U R'' U R'' F R F'' U2 R'' F R F'''),
        (17, 'y2 F R'' F'' R U S'' R U'' R'' S'),
        (17, 'y2 F R'' F'' R2 r'' U R U'' R'' U'' M'''),
        (17, 'y'' F'' r U r'' U'' S r'' F r S'''),
        (18, 'y (R U2 R'') (R'' F R F'') U2 M'' (U R U'' r'')'),
        (18, 'y R U2 R2 F R F'' U2 M'' U R U'' r'''),
        (18, 'r U R'' U R U2 r2 U'' R U'' R'' U2 r'),
        (18, 'y F S'' R U'' R'' S R U2 R'' U'' F'''),
        (18, 'R D r'' U'' r D'' R'' U'' R2 F R F'' R'),
        (19, 'M U (R U R'' U'') M'' (R'' F R F'')'),
        (19, 'y S'' R U R'' S U'' R'' F R F'''),
        (19, 'M U R U R'' U'' M'' R'' F R F'''),
        (19, 'R'' U2 F R U R'' U'' F2 U2 F R'),
        (19, 'r'' R U R U R'' U'' r R2 F R F'''),
        (20, '(r U R'' U'') M2 (U R U'' R'') U'' M'''),
        (20, 'r U R'' U'' M2 U R U'' R'' U'' M'''),
        (20, 'M'' U2 M U2 M'' U M U2 M'' U2 M'),
        (20, 'S'' R U R'' S U'' M'' U R U'' r'''),
        (20, 'S R'' U'' R U R U R U'' R'' S'''),
        (21, '(R U R'' U) (R U'' R'' U) (R U2 R'')'),
        (21, 'R U R'' U R U'' R'' U R U2 R'''),
        (21, 'y R U2 R'' U'' R U R'' U'' R U'' R'''),
        (21, 'y F R U R'' U'' R U R'' U'' R U R'' U'' F'''),
        (21, 'R'' U'' R U'' R'' U R U'' R'' U2 R'),
        (22, 'R U2 (R2'' U'') (R2 U'') (R2'' U'') U'' R'),
        (22, 'R U2 R2 U'' R2 U'' R2 U2 R'),
        (22, 'R'' U2 R2 U R2 U R2 U2 R'''),
        (22, 'f R U R'' U'' S'' R U R'' U'' F'''),
        (22, 'f R U R'' U'' f'' F R U R'' U'' F'''),
        (23, 'R2 D (R'' U2 R) D'' (R'' U2 R'')'),
        (23, 'R2 D R'' U2 R D'' R'' U2 R'''),
        (23, 'y2 R2 D'' R U2 R'' D R U2 R'),
        (23, 'R U R'' U R U2 R2 U'' R U'' R'' U2 R'),
        (23, 'y R U R'' U'' R U'' R'' U2 R U'' R'' U2 R U R'''),
        (24, '(r U R'' U'') (r'' F R F'')'),
        (24, 'r U R'' U'' r'' F R F'''),
        (24, 'y2 R'' F'' r U R U'' r'' F'),
        (24, 'y'' x'' R U R'' D R U'' R'' D'' x'),
        (24, 'y R U R D R'' U'' R D'' R2'),
        (25, 'y (F'' r U R'') (U'' r'' F R)'),
        (25, 'R U2 R D R'' U2 R D'' R2'),
        (25, 'y F'' r U R'' U'' r'' F R'),
        (25, 'F R'' F'' r U R U'' r'''),
        (25, 'x R'' U R D'' R'' U'' R D x'''),
        (26, 'y R U2 (R'' U'' R U'') R'''),
        (26, 'y R U2 R'' U'' R U'' R'''),
        (26, 'R'' U'' R U'' R'' U2 R'),
        (26, 'y2 L'' U'' L U'' L'' U2 L'),
        (26, 'y2 L'' U R U'' L U R'''),
        (27, '(R U R'' U) (R U2 R'')'),
        (27, 'R U R'' U R U2 R'''),
        (27, 'y'' R'' U2 R U R'' U R'),
        (27, 'y L'' U2 L U L'' U L'),
        (27, 'y2 L U L'' U L U2 L'''),
        (28, '(r U R'' U'') M (U R U'' R'')'),
        (28, 'r U R'' U'' M U R U'' R'''),
        (28, 'r U R'' U'' r'' R U R U'' R'''),
        (28, 'R'' F R S R'' F'' R S'''),
        (28, 'y2 M'' U M U2 M'' U M'),
        (29, 'y (R U R'') U'' (R U'' R'') (F'' U'' F) (R U R'')'),
        (29, 'r2 D'' r U r'' D r2 U'' r'' U'' r'),
        (29, 'y R U R'' U'' R U'' R'' F'' U'' F R U R'''),
        (29, 'y S'' R U R'' U'' R'' F R F'' U S'),
        (29, 'M U R U R'' U'' R'' F R F'' M'''),
        (30, 'y2 F U (R U2 R'') U'' (R U2 R'') U'' F'''),
        (30, 'y'' r'' D'' r U'' r'' D r2 U'' r'' U r U r'''),
        (30, 'y2 F U R U2 R'' U'' R U2 R'' U'' F'''),
        (30, 'y2 F R'' F R2 U'' R'' U'' R U R'' F2'),
        (30, 'y S'' R'' U'' R f R'' U R U'' F'''),
        (31, '(R'' U'' F) (U R U'' R'') F'' R'),
        (31, 'R'' U'' F U R U'' R'' F'' R'),
        (31, 'y2 S'' L'' U'' L U L F'' L'' f'),
        (31, 'y S R U R'' U'' f'' U'' F'),
        (31, 'y'' F R'' F'' R U R U R'' U'' R U'' R'''),
        (32, 'S (R U R'' U'') (R'' F R f'')'),
        (32, 'S R U R'' U'' R'' F R f'''),
        (32, 'y2 L U F'' U'' L'' U L F L'''),
        (32, 'R U B'' U'' R'' U R B R'''),
        (32, 'y'' R'' F R F'' U'' r U'' r'' U r U r'''),
        (33, '(R U R'' U'') (R'' F R F'')'),
        (33, 'R U R'' U'' R'' F R F'''),
        (33, 'y2 L'' U'' L U L F'' L'' F'),
        (33, 'y2 r'' F'' r U r U'' r'' F'),
        (33, 'R U R'' F'' U'' F R U'' R'''),
        (34, 'y2 R U R2 U'' R'' F (R U R U'') F'''),
        (34, 'y f R f'' U'' r'' U'' R U M'''),
        (34, 'y2 R U R2 U'' R'' F R U R U'' F'''),
        (34, 'F R U R'' U'' R'' F'' r U R U'' r'''),
        (34, 'y2 R U R'' U'' B'' R'' F R F'' B'),
        (35, '(R U2 R'') (R'' F R F'') (R U2 R'')'),
        (35, 'R U2 R2 F R F'' R U2 R'''),
        (35, 'f R U R'' U'' f'' R U R'' U R U2 R'''),
        (35, 'R U2 R'' d'' R'' F R U'' R'' F'' R'),
        (35, 'y L'' U2 L2 F'' L'' F L'' U2 L'),
        (36, 'y2 (L'' U'' L U'') (L'' U L U) (L F'' L'' F)'),
        (36, 'y R U R2 F'' U'' F U R2 U2 R'''),
        (36, 'y2 L'' U'' L U'' L'' U L U L F'' L'' F'),
        (36, 'y2 R U R'' F'' R U R'' U'' R'' F R U'' R'' F R F'''),
        (36, 'R U R'' U'' F'' U2 F U R U R'''),
        (37, 'F R (U'' R'' U'') (R U R'') F'''),
        (37, 'F R'' F'' R U R U'' R'''),
        (37, 'F R U'' R'' U'' R U R'' F'''),
        (37, 'y F'' r U r'' U'' r'' F r'),
        (37, 'y2 r2 D'' r U'' r'' D r U r'),
        (38, '(R U R'' U) (R U'' R'' U'') (R'' F R F'')'),
        (38, 'R U R'' U R U'' R'' U'' R'' F R F'''),
        (38, 'y F R U'' R'' S U'' R U R'' f'''),
        (38, 'r U R'' U'' r'' F R U R U'' R'' F'''),
        (38, 'y2 L U L'' U L U'' L'' U'' L'' B L B'''),
        (39, 'y L F'' (L'' U'' L U) F U'' L'''),
        (39, 'y'' f'' r U r'' U'' r'' F r S'),
        (39, 'y'' R U R'' F'' U'' F U R U2 R'''),
        (39, 'y L F'' L'' U'' L U F U'' L'''),
        (39, 'y'' f'' L F L'' U'' L'' U L S'),
        (40, 'y R'' F (R U R'' U'') F'' U R'),
        (40, 'y R'' F R U R'' U'' F'' U R'),
        (40, 'y'' f R'' F'' R U R U'' R'' S'''),
        (40, 'R r D r'' U r D'' r'' U'' R'''),
        (40, 'y'' L'' U'' L F U F'' U'' L'' U2 L'),
        (41, 'y2 (R U R'' U) (R U2 R'') F (R U R'' U'') F'''),
        (41, 'y2 R U R'' U R U2 R'' F R U R'' U'' F'''),
        (41, 'y2 F U R2 D R'' U'' R D'' R2 F'''),
        (41, 'y'' S U'' R'' F'' U'' F U R S'''),
        (41, 'M U'' F'' L'' U'' L U F M'''),
        (42, '(R'' U'' R U'') (R'' U2 R) F (R U R'' U'') F'''),
        (42, 'R'' U'' R U'' R'' U2 R F R U R'' U'' F'''),
        (42, 'y F S'' R U R'' U'' F'' U S'),
        (42, 'y R'' F R F'' R'' F R F'' R U R'' U'' R U R'''),
        (42, 'y R'' U'' F2 u'' R U R'' D R2 B'),
        (43, 'y R'' U'' (F'' U F) R'),
        (43, 'y R'' U'' F'' U F R'),
        (43, 'y2 F'' U'' L'' U L F'),
        (43, 'f'' L'' U'' L U f'),
        (43, 'B'' U'' R'' U R B'),
        (44, 'f (R U R'' U'') f'''),
        (44, 'f R U R'' U'' f'''),
        (44, 'y2 F U R U'' R'' F'''),
        (44, 'y R U B U'' B'' R'''),
        (44, 'y'' L U F U'' F'' L'''),
        (45, 'F (R U R'' U'') F'''),
        (45, 'F R U R'' U'' F'''),
        (45, 'y R'' F'' U'' F U R'),
        (45, 'y2 f U R U'' R'' f'''),
        (45, 'y2 F'' L'' U'' L U F'),
        (46, 'R'' U'' (R'' F R F'') U R'),
        (46, 'R'' U'' R'' F R F'' U R'),
        (46, 'R'' F'' U'' F R U'' R'' U2 R'),
        (46, 'y F R U R'' U'' F'' U'' R U R'' U R U2 R'''),
        (46, 'l'' U2 L2 F'' L'' F U L'' U l'),
        (47, 'F'' (L'' U'' L U) (L'' U'' L U) F'),
        (47, 'y'' F R'' F'' R U2 R U'' R'' U R U2 R'''),
        (47, 'F'' L'' U'' L U L'' U'' L U F'),
        (47, 'R'' U'' R'' F R F'' R'' F R F'' U R'),
        (47, 'y'' R'' F'' U'' F U F'' U'' F U R'),
        (48, 'F (R U R'' U'') (R U R'' U'') F'''),
        (48, 'F R U R'' U'' R U R'' U'' F'''),
        (48, 'y2 f U R U'' R'' U R U'' R'' f'''),
        (48, 'R U2 R'' U'' R U R'' U2 R'' F R F'''),
        (48, 'F R'' F'' U2 R U R'' U R2 U2 R'''),
        (49, 'y2 r U'' (r2 U) (r2 U) (r2) U'' r'),
        (49, 'y2 r U'' r2 U r2 U r2 U'' r'),
        (49, 'l U'' l2 U l2 U l2 U'' l'),
        (49, 'R B'' R2 F R2 B R2 F'' R'),
        (49, 'y2 R'' F R'' F'' R2 U2 B'' R B R'''),
        (50, 'r'' U (r2 U'') (r2 U'') (r2) U r'''),
        (50, 'r'' U r2 U'' r2 U'' r2 U r'''),
        (50, 'y2 R'' F R2 B'' R2 F'' R2 B R'''),
        (50, 'y'' R U2 R'' U'' R U'' R'' F R U R'' U'' F'''),
        (50, 'y2 l'' U l2 U'' l2 U'' l2 U l'''),
        (51, 'f (R U R'' U'') (R U R'' U'') f'''),
        (51, 'y2 F U R U'' R'' U R U'' R'' F'''),
        (51, 'f R U R'' U'' R U R'' U'' f'''),
        (51, 'y'' R'' U'' R'' F R F'' R U'' R'' U2 R'),
        (51, 'y r'' F'' U'' F U F'' U'' F U r'),
        (52, 'y2 R'' (F'' U'' F U'') (R U R'' U) R'),
        (52, 'y2 R'' F'' U'' F U'' R U R'' U R'),
        (52, 'R U R'' U R U'' B U'' B'' R'''),
        (52, 'R U R'' U R d'' R U'' R'' F'''),
        (52, 'R U R'' U R U'' y R U'' R'' F'''),
        (53, '(r'' U'' R U'') (R'' U R U'') (R'' U2 r)'),
        (53, 'r'' U'' R U'' R'' U R U'' R'' U2 r'),
        (53, 'y2 l'' U'' L U'' L'' U L U'' L'' U2 l'),
        (53, 'y r'' U2 R U R'' U'' R U R'' U r'),
        (53, 'y'' l'' U2 L U L'' U'' L U L'' U l'),
        (54, '(r U R'' U) (R U'' R'' U) (R U2 r'')'),
        (54, 'r U R'' U R U'' R'' U R U2 r'''),
        (54, 'y'' r U2 R'' U'' R U R'' U'' R U'' r'''),
        (54, 'y'' r U r'' R U R'' U'' R U R'' U'' r U'' r'''),
        (54, 'y2 l U L'' U L U'' L'' U L U2 l'''),
        (55, 'R U2 R2 (U'' R U'' R'') U2 (F R F'')'),
        (55, 'y R'' F U R U'' R2 F'' R2 U R'' U'' R'),
        (55, 'y R'' F R U R U'' R2 F'' R2 U'' R'' U R U R'''),
        (55, 'R U2 R2 U'' R U'' R'' U2 F R F'''),
        (55, 'r U2 R2 F R F'' U2 r'' F R F'''),
        (56, '(r U r'') (U R U'' R'') (U R U'' R'') (r U'' r'')'),
        (56, 'r U r'' U R U'' R'' U R U'' R'' r U'' r'''),
        (56, 'r U r'' U R U'' R'' M'' U R U2 r'''),
        (56, 'F R U R'' U'' R F'' r U R'' U'' r'''),
        (56, 'r'' U'' r U'' R'' U R U'' R'' U R r'' U r'),
        (57, '(R U R'' U'') M'' (U R U'' r'')'),
        (57, 'R U R'' U'' M'' U R U'' r'''),
        (57, 'y R U'' R'' S'' R U R'' S'),
        (57, 'y R U R'' S'' R U'' R'' S'),
        (57, 'R U R'' U'' R'' r U R U'' r''')
)
INSERT INTO "Algorithms" ("Moves", "AlgorithmCaseId", "UserId")
SELECT oll_algorithms.moves, algorithm_cases."Id", NULL
FROM oll_algorithms
JOIN "AlgorithmCases" AS algorithm_cases
    ON algorithm_cases."CaseNumber" = oll_algorithms.case_number
JOIN "AlgorithmSets" AS algorithm_sets
    ON algorithm_sets."Id" = algorithm_cases."AlgorithmSetId"
   AND algorithm_sets."Name" = 'OLL'
WHERE NOT EXISTS (
    SELECT 1
    FROM "Algorithms" AS existing_algorithm
    WHERE existing_algorithm."AlgorithmCaseId" = algorithm_cases."Id"
      AND existing_algorithm."Moves" = oll_algorithms.moves
);

COMMIT;
