-- Seeds each standard OLL algorithm plus its first four listed alternatives from oll-algs.pdf.
-- Run this after AlgorithmSeeder has created the OLL set and its cases.
-- The case labels below intentionally match AlgorithmSeeder exactly.

BEGIN;

WITH oll_algorithms(case_name, moves) AS (
    VALUES
        ('Dot Case', '(R U2 R'') (R'' F R F'') U2 (R'' F R F'')'),
        ('Dot Case', 'R U2 R2 F R F'' U2 R'' F R F'''),
        ('Dot Case', 'y R U'' R2 D'' r U'' r'' D R2 U R'''),
        ('Dot Case', 'f R U R'' U'' R f'' U'' r'' U'' R U M'''),
        ('Dot Case', 'L'' U2 L2 F'' L'' F U2 L F'' L'' F'),
        ('Dot Case', 'F (R U R'' U'') F'' f (R U R'' U'') f'''),
        ('Dot Case', 'y'' R U'' R2 D'' r U r'' D R2 U R'''),
        ('Dot Case', 'F R U R'' U'' S R U R'' U'' f'''),
        ('Dot Case', 'F R U R'' U'' F'' f R U R'' U'' f'''),
        ('Dot Case', 'y r U r'' U2 R U2 R'' U2 r U'' r'''),
        ('Dot Case', 'y'' f (R U R'' U'') f'' (U'') F (R U R'' U'') F'''),
        ('Dot Case', 'y'' f R U R'' U'' f'' U'' F R U R'' U'' F'''),
        ('Dot Case', 'y R'' F2 R2 U2 R'' F R U2 R2 F2 R'),
        ('Dot Case', 'r'' R2 U R'' U r U2 r'' U M'''),
        ('Dot Case', 'M R U R'' U r U2 r'' U M'''),
        ('Dot Case', 'y'' f (R U R'' U'') f'' (U) F (R U R'' U'') F'''),
        ('Dot Case', 'y'' R'' F2 R2 U2 R'' F'' R U2 R2 F2 R'),
        ('Dot Case', 'y'' f R U R'' U'' f'' U F R U R'' U'' F'''),
        ('Dot Case', 'R'' F R F'' U'' S R'' U'' R U R S'''),
        ('Dot Case', 'y F U R U'' R'' F'' U'' F R U R'' U'' F'''),
        ('Square Shapes', 'r'' U2 (R U R'' U) r'),
        ('Square Shapes', 'r'' U2 R U R'' U r'),
        ('Square Shapes', 'y2 l'' U2 L U L'' U l'),
        ('Square Shapes', 'y2 R'' F2 r U r'' F R'),
        ('Square Shapes', 'y2 R'' F2 L F L'' F R'),
        ('Square Shapes', 'r U2 (R'' U'' R U'') r'''),
        ('Square Shapes', 'r U2 R'' U'' R U'' r'''),
        ('Square Shapes', 'F U'' R2 D R'' U'' R D'' R2 U F'''),
        ('Square Shapes', 'y2 l U2 L'' U'' L U'' l'''),
        ('Square Shapes', 'L F2 l'' U'' l F'' L'''),
        ('Lightning Shapes', 'r (U R'' U R) U2 r'''),
        ('Lightning Shapes', 'r U R'' U R U2 r'''),
        ('Lightning Shapes', 'S'' R U R'' U R U2 R'' U S'),
        ('Lightning Shapes', 'L'' U2 L U2 L F'' L'' F'),
        ('Lightning Shapes', 'y2 f R U R'' U'' f'' y2 F R'' F'' r U R U'' r'''),
        ('Lightning Shapes', 'y2 r'' (U'' R U'' R'') U2 r'),
        ('Lightning Shapes', 'y2 r'' U'' R U'' R'' U2 r'),
        ('Lightning Shapes', 'l'' U'' L U'' L'' U2 l'),
        ('Lightning Shapes', 'R U2 R'' U2 R'' F R F'''),
        ('Lightning Shapes', 'R'' F'' r U'' r'' F2 R'),
        ('Fish Shapes', 'y (R U R'' U'') (R'' F R) (R U R'' U'') F'''),
        ('Fish Shapes', 'y R U R'' U'' R'' F R2 U R'' U'' F'''),
        ('Fish Shapes', 'R U2 R'' U'' S'' R U'' R'' S'),
        ('Fish Shapes', 'y2 F'' U'' F r U'' r'' U r U r'''),
        ('Fish Shapes', 'y'' L'' U'' L U'' L F'' L'' F L'' U2 L'),
        ('Fish Shapes', '(R U R'' U) (R'' F R F'') (R U2 R'')'),
        ('Fish Shapes', 'R U R'' U R'' F R F'' R U2 R'''),
        ('Fish Shapes', 'y F U F'' R'' F R U'' R'' F'' R'),
        ('Fish Shapes', 'y M'' R'' U2 R U R'' U R U M'),
        ('Fish Shapes', 'y2 L'' U'' L U L F'' L2 U'' L U F'),
        ('Lightning Shapes', 'M (R U R'' U R U2 R'') U M'''),
        ('Lightning Shapes', 'r'' R2 U R'' U R U2 R'' U M'''),
        ('Lightning Shapes', 'y2 r U R'' U R'' F R F'' R U2 r'''),
        ('Lightning Shapes', 'S R U R'' U R U2 R'' U2 S'''),
        ('Lightning Shapes', 'M R U R'' U R U2 R'' U M'''),
        ('Lightning Shapes', 'y'' M'' (R'' U'' R U'' R'' U2 R) U'' M'),
        ('Lightning Shapes', 'y'' M'' R'' U'' R U'' R'' U2 R U'' M'),
        ('Lightning Shapes', 'F R U R'' U'' F'' U F R U R'' U'' F'''),
        ('Lightning Shapes', 'y'' S R'' U'' R U'' R'' U2 R U2 S'''),
        ('Lightning Shapes', 'y M L'' U'' L U'' L'' U2 L U'' M'''),
        ('Knight Move Shapes', '(r U'' r'') U'' (r U r'') (F'' U F)'),
        ('Knight Move Shapes', 'F U R U2 R'' U'' R U R'' F'''),
        ('Knight Move Shapes', 'F U R U'' R2 F'' R U R U'' R'''),
        ('Knight Move Shapes', 'r U'' r'' U'' r U r'' F'' U F'),
        ('Knight Move Shapes', 'y2 f R U R2 U'' R'' U R U'' f'''),
        ('Knight Move Shapes', 'R'' F (R U R'') F'' R (F U'' F'')'),
        ('Knight Move Shapes', 'R'' F R U R'' F'' R F U'' F'''),
        ('Knight Move Shapes', 'r U R'' U'' r'' F R2 U R'' U'' F'''),
        ('Knight Move Shapes', 'l'' U l U l'' U'' l F U'' F'''),
        ('Knight Move Shapes', 'S R U R'' U'' R'' F R2 U R'' U'' f'''),
        ('Knight Move Shapes', '(r'' U'' r) (R'' U'' R U) (r'' U r)'),
        ('Knight Move Shapes', 'r'' U'' r R'' U'' R U r'' U r'),
        ('Knight Move Shapes', 'y2 l'' U'' l L'' U'' L U l'' U l'),
        ('Knight Move Shapes', 'r'' U'' M'' U'' R U r'' U r'),
        ('Knight Move Shapes', 'y2 R'' F'' R L'' U'' L U R'' F R'),
        ('Knight Move Shapes', '(r U r'') (R U R'' U'') (r U'' r'')'),
        ('Knight Move Shapes', 'r U r'' R U R'' U'' r U'' r'''),
        ('Knight Move Shapes', 'r U M U R'' U'' r U'' r'''),
        ('Knight Move Shapes', 'y2 R'' F R U R'' U'' F'' R U'' R'' U2 R'),
        ('Knight Move Shapes', 'y2 l U l'' L U L'' U'' l U'' l'''),
        ('Dot Case', '(R U R'' U) (R'' F R F'') U2 (R'' F R F'')'),
        ('Dot Case', 'R U R'' U R'' F R F'' U2 R'' F R F'''),
        ('Dot Case', 'y2 F R'' F'' R U S'' R U'' R'' S'),
        ('Dot Case', 'y2 F R'' F'' R2 r'' U R U'' R'' U'' M'''),
        ('Dot Case', 'y'' F'' r U r'' U'' S r'' F r S'''),
        ('Dot Case', 'y (R U2 R'') (R'' F R F'') U2 M'' (U R U'' r'')'),
        ('Dot Case', 'y R U2 R2 F R F'' U2 M'' U R U'' r'''),
        ('Dot Case', 'r U R'' U R U2 r2 U'' R U'' R'' U2 r'),
        ('Dot Case', 'y F S'' R U'' R'' S R U2 R'' U'' F'''),
        ('Dot Case', 'R D r'' U'' r D'' R'' U'' R2 F R F'' R'),
        ('Dot Case', 'M U (R U R'' U'') M'' (R'' F R F'')'),
        ('Dot Case', 'y S'' R U R'' S U'' R'' F R F'''),
        ('Dot Case', 'M U R U R'' U'' M'' R'' F R F'''),
        ('Dot Case', 'R'' U2 F R U R'' U'' F2 U2 F R'),
        ('Dot Case', 'r'' R U R U R'' U'' r R2 F R F'''),
        ('Dot Case', '(r U R'' U'') M2 (U R U'' R'') U'' M'''),
        ('Dot Case', 'r U R'' U'' M2 U R U'' R'' U'' M'''),
        ('Dot Case', 'M'' U2 M U2 M'' U M U2 M'' U2 M'),
        ('Dot Case', 'S'' R U R'' S U'' M'' U R U'' r'''),
        ('Dot Case', 'S R'' U'' R U R U R U'' R'' S'''),
        ('OCLL', '(R U R'' U) (R U'' R'' U) (R U2 R'')'),
        ('OCLL', 'R U R'' U R U'' R'' U R U2 R'''),
        ('OCLL', 'y R U2 R'' U'' R U R'' U'' R U'' R'''),
        ('OCLL', 'y F R U R'' U'' R U R'' U'' R U R'' U'' F'''),
        ('OCLL', 'R'' U'' R U'' R'' U R U'' R'' U2 R'),
        ('OCLL', 'R U2 (R2'' U'') (R2 U'') (R2'' U'') U'' R'),
        ('OCLL', 'R U2 R2 U'' R2 U'' R2 U2 R'),
        ('OCLL', 'R'' U2 R2 U R2 U R2 U2 R'''),
        ('OCLL', 'f R U R'' U'' S'' R U R'' U'' F'''),
        ('OCLL', 'f R U R'' U'' f'' F R U R'' U'' F'''),
        ('OCLL', 'R2 D (R'' U2 R) D'' (R'' U2 R'')'),
        ('OCLL', 'R2 D R'' U2 R D'' R'' U2 R'''),
        ('OCLL', 'y2 R2 D'' R U2 R'' D R U2 R'),
        ('OCLL', 'R U R'' U R U2 R2 U'' R U'' R'' U2 R'),
        ('OCLL', 'y R U R'' U'' R U'' R'' U2 R U'' R'' U2 R U R'''),
        ('OCLL', '(r U R'' U'') (r'' F R F'')'),
        ('OCLL', 'r U R'' U'' r'' F R F'''),
        ('OCLL', 'y2 R'' F'' r U R U'' r'' F'),
        ('OCLL', 'y'' x'' R U R'' D R U'' R'' D'' x'),
        ('OCLL', 'y R U R D R'' U'' R D'' R2'),
        ('OCLL', 'y (F'' r U R'') (U'' r'' F R)'),
        ('OCLL', 'R U2 R D R'' U2 R D'' R2'),
        ('OCLL', 'y F'' r U R'' U'' r'' F R'),
        ('OCLL', 'F R'' F'' r U R U'' r'''),
        ('OCLL', 'x R'' U R D'' R'' U'' R D x'''),
        ('OCLL', 'y R U2 (R'' U'' R U'') R'''),
        ('OCLL', 'y R U2 R'' U'' R U'' R'''),
        ('OCLL', 'R'' U'' R U'' R'' U2 R'),
        ('OCLL', 'y2 L'' U'' L U'' L'' U2 L'),
        ('OCLL', 'y2 L'' U R U'' L U R'''),
        ('OCLL', '(R U R'' U) (R U2 R'')'),
        ('OCLL', 'R U R'' U R U2 R'''),
        ('OCLL', 'y'' R'' U2 R U R'' U R'),
        ('OCLL', 'y L'' U2 L U L'' U L'),
        ('OCLL', 'y2 L U L'' U L U2 L'''),
        ('All Corners Orientated', '(r U R'' U'') M (U R U'' R'')'),
        ('All Corners Orientated', 'r U R'' U'' M U R U'' R'''),
        ('All Corners Orientated', 'r U R'' U'' r'' R U R U'' R'''),
        ('All Corners Orientated', 'R'' F R S R'' F'' R S'''),
        ('All Corners Orientated', 'y2 M'' U M U2 M'' U M'),
        ('Awkward Shapes', 'y (R U R'') U'' (R U'' R'') (F'' U'' F) (R U R'')'),
        ('Awkward Shapes', 'r2 D'' r U r'' D r2 U'' r'' U'' r'),
        ('Awkward Shapes', 'y R U R'' U'' R U'' R'' F'' U'' F R U R'''),
        ('Awkward Shapes', 'y S'' R U R'' U'' R'' F R F'' U S'),
        ('Awkward Shapes', 'M U R U R'' U'' R'' F R F'' M'''),
        ('Awkward Shapes', 'y2 F U (R U2 R'') U'' (R U2 R'') U'' F'''),
        ('Awkward Shapes', 'y'' r'' D'' r U'' r'' D r2 U'' r'' U r U r'''),
        ('Awkward Shapes', 'y2 F U R U2 R'' U'' R U2 R'' U'' F'''),
        ('Awkward Shapes', 'y2 F R'' F R2 U'' R'' U'' R U R'' F2'),
        ('Awkward Shapes', 'y S'' R'' U'' R f R'' U R U'' F'''),
        ('P Shapes', '(R'' U'' F) (U R U'' R'') F'' R'),
        ('P Shapes', 'R'' U'' F U R U'' R'' F'' R'),
        ('P Shapes', 'y2 S'' L'' U'' L U L F'' L'' f'),
        ('P Shapes', 'y S R U R'' U'' f'' U'' F'),
        ('P Shapes', 'y'' F R'' F'' R U R U R'' U'' R U'' R'''),
        ('P Shapes', 'S (R U R'' U'') (R'' F R f'')'),
        ('P Shapes', 'S R U R'' U'' R'' F R f'''),
        ('P Shapes', 'y2 L U F'' U'' L'' U L F L'''),
        ('P Shapes', 'R U B'' U'' R'' U R B R'''),
        ('P Shapes', 'y'' R'' F R F'' U'' r U'' r'' U r U r'''),
        ('T Shapes', '(R U R'' U'') (R'' F R F'')'),
        ('T Shapes', 'R U R'' U'' R'' F R F'''),
        ('T Shapes', 'y2 L'' U'' L U L F'' L'' F'),
        ('T Shapes', 'y2 r'' F'' r U r U'' r'' F'),
        ('T Shapes', 'R U R'' F'' U'' F R U'' R'''),
        ('C Shapes', 'y2 R U R2 U'' R'' F (R U R U'') F'''),
        ('C Shapes', 'y f R f'' U'' r'' U'' R U M'''),
        ('C Shapes', 'y2 R U R2 U'' R'' F R U R U'' F'''),
        ('C Shapes', 'F R U R'' U'' R'' F'' r U R U'' r'''),
        ('C Shapes', 'y2 R U R'' U'' B'' R'' F R F'' B'),
        ('Fish Shapes', '(R U2 R'') (R'' F R F'') (R U2 R'')'),
        ('Fish Shapes', 'R U2 R2 F R F'' R U2 R'''),
        ('Fish Shapes', 'f R U R'' U'' f'' R U R'' U R U2 R'''),
        ('Fish Shapes', 'R U2 R'' d'' R'' F R U'' R'' F'' R'),
        ('Fish Shapes', 'y L'' U2 L2 F'' L'' F L'' U2 L'),
        ('W Shapes', 'y2 (L'' U'' L U'') (L'' U L U) (L F'' L'' F)'),
        ('W Shapes', 'y R U R2 F'' U'' F U R2 U2 R'''),
        ('W Shapes', 'y2 L'' U'' L U'' L'' U L U L F'' L'' F'),
        ('W Shapes', 'y2 R U R'' F'' R U R'' U'' R'' F R U'' R'' F R F'''),
        ('W Shapes', 'R U R'' U'' F'' U2 F U R U R'''),
        ('Fish Shapes', 'F R (U'' R'' U'') (R U R'') F'''),
        ('Fish Shapes', 'F R'' F'' R U R U'' R'''),
        ('Fish Shapes', 'F R U'' R'' U'' R U R'' F'''),
        ('Fish Shapes', 'y F'' r U r'' U'' r'' F r'),
        ('Fish Shapes', 'y2 r2 D'' r U'' r'' D r U r'),
        ('W Shapes', '(R U R'' U) (R U'' R'' U'') (R'' F R F'')'),
        ('W Shapes', 'R U R'' U R U'' R'' U'' R'' F R F'''),
        ('W Shapes', 'y F R U'' R'' S U'' R U R'' f'''),
        ('W Shapes', 'r U R'' U'' r'' F R U R U'' R'' F'''),
        ('W Shapes', 'y2 L U L'' U L U'' L'' U'' L'' B L B'''),
        ('Lightning Shapes', 'y L F'' (L'' U'' L U) F U'' L'''),
        ('Lightning Shapes', 'y'' f'' r U r'' U'' r'' F r S'),
        ('Lightning Shapes', 'y'' R U R'' F'' U'' F U R U2 R'''),
        ('Lightning Shapes', 'y L F'' L'' U'' L U F U'' L'''),
        ('Lightning Shapes', 'y'' f'' L F L'' U'' L'' U L S'),
        ('Lightning Shapes', 'y R'' F (R U R'' U'') F'' U R'),
        ('Lightning Shapes', 'y R'' F R U R'' U'' F'' U R'),
        ('Lightning Shapes', 'y'' f R'' F'' R U R U'' R'' S'''),
        ('Lightning Shapes', 'R r D r'' U r D'' r'' U'' R'''),
        ('Lightning Shapes', 'y'' L'' U'' L F U F'' U'' L'' U2 L'),
        ('Awkward Shapes', 'y2 (R U R'' U) (R U2 R'') F (R U R'' U'') F'''),
        ('Awkward Shapes', 'y2 R U R'' U R U2 R'' F R U R'' U'' F'''),
        ('Awkward Shapes', 'y2 F U R2 D R'' U'' R D'' R2 F'''),
        ('Awkward Shapes', 'y'' S U'' R'' F'' U'' F U R S'''),
        ('Awkward Shapes', 'M U'' F'' L'' U'' L U F M'''),
        ('Awkward Shapes', '(R'' U'' R U'') (R'' U2 R) F (R U R'' U'') F'''),
        ('Awkward Shapes', 'R'' U'' R U'' R'' U2 R F R U R'' U'' F'''),
        ('Awkward Shapes', 'y F S'' R U R'' U'' F'' U S'),
        ('Awkward Shapes', 'y R'' F R F'' R'' F R F'' R U R'' U'' R U R'''),
        ('Awkward Shapes', 'y R'' U'' F2 u'' R U R'' D R2 B'),
        ('P Shapes', 'y R'' U'' (F'' U F) R'),
        ('P Shapes', 'y R'' U'' F'' U F R'),
        ('P Shapes', 'y2 F'' U'' L'' U L F'),
        ('P Shapes', 'f'' L'' U'' L U f'),
        ('P Shapes', 'B'' U'' R'' U R B'),
        ('P Shapes', 'f (R U R'' U'') f'''),
        ('P Shapes', 'f R U R'' U'' f'''),
        ('P Shapes', 'y2 F U R U'' R'' F'''),
        ('P Shapes', 'y R U B U'' B'' R'''),
        ('P Shapes', 'y'' L U F U'' F'' L'''),
        ('T Shapes', 'F (R U R'' U'') F'''),
        ('T Shapes', 'F R U R'' U'' F'''),
        ('T Shapes', 'y R'' F'' U'' F U R'),
        ('T Shapes', 'y2 f U R U'' R'' f'''),
        ('T Shapes', 'y2 F'' L'' U'' L U F'),
        ('C Shapes', 'R'' U'' (R'' F R F'') U R'),
        ('C Shapes', 'R'' U'' R'' F R F'' U R'),
        ('C Shapes', 'R'' F'' U'' F R U'' R'' U2 R'),
        ('C Shapes', 'y F R U R'' U'' F'' U'' R U R'' U R U2 R'''),
        ('C Shapes', 'l'' U2 L2 F'' L'' F U L'' U l'),
        ('L shapes', 'F'' (L'' U'' L U) (L'' U'' L U) F'),
        ('L shapes', 'y'' F R'' F'' R U2 R U'' R'' U R U2 R'''),
        ('L shapes', 'F'' L'' U'' L U L'' U'' L U F'),
        ('L shapes', 'R'' U'' R'' F R F'' R'' F R F'' U R'),
        ('L shapes', 'y'' R'' F'' U'' F U F'' U'' F U R'),
        ('L shapes', 'F (R U R'' U'') (R U R'' U'') F'''),
        ('L shapes', 'F R U R'' U'' R U R'' U'' F'''),
        ('L shapes', 'y2 f U R U'' R'' U R U'' R'' f'''),
        ('L shapes', 'R U2 R'' U'' R U R'' U2 R'' F R F'''),
        ('L shapes', 'F R'' F'' U2 R U R'' U R2 U2 R'''),
        ('L shapes', 'y2 r U'' (r2 U) (r2 U) (r2) U'' r'),
        ('L shapes', 'y2 r U'' r2 U r2 U r2 U'' r'),
        ('L shapes', 'l U'' l2 U l2 U l2 U'' l'),
        ('L shapes', 'R B'' R2 F R2 B R2 F'' R'),
        ('L shapes', 'y2 R'' F R'' F'' R2 U2 B'' R B R'''),
        ('L shapes', 'r'' U (r2 U'') (r2 U'') (r2) U r'''),
        ('L shapes', 'r'' U r2 U'' r2 U'' r2 U r'''),
        ('L shapes', 'y2 R'' F R2 B'' R2 F'' R2 B R'''),
        ('L shapes', 'y'' R U2 R'' U'' R U'' R'' F R U R'' U'' F'''),
        ('L shapes', 'y2 l'' U l2 U'' l2 U'' l2 U l'''),
        ('Line Shapes', 'f (R U R'' U'') (R U R'' U'') f'''),
        ('Line Shapes', 'y2 F U R U'' R'' U R U'' R'' F'''),
        ('Line Shapes', 'f R U R'' U'' R U R'' U'' f'''),
        ('Line Shapes', 'y'' R'' U'' R'' F R F'' R U'' R'' U2 R'),
        ('Line Shapes', 'y r'' F'' U'' F U F'' U'' F U r'),
        ('Line Shapes', 'y2 R'' (F'' U'' F U'') (R U R'' U) R'),
        ('Line Shapes', 'y2 R'' F'' U'' F U'' R U R'' U R'),
        ('Line Shapes', 'R U R'' U R U'' B U'' B'' R'''),
        ('Line Shapes', 'R U R'' U R d'' R U'' R'' F'''),
        ('Line Shapes', 'R U R'' U R U'' y R U'' R'' F'''),
        ('L shapes', '(r'' U'' R U'') (R'' U R U'') (R'' U2 r)'),
        ('L shapes', 'r'' U'' R U'' R'' U R U'' R'' U2 r'),
        ('L shapes', 'y2 l'' U'' L U'' L'' U L U'' L'' U2 l'),
        ('L shapes', 'y r'' U2 R U R'' U'' R U R'' U r'),
        ('L shapes', 'y'' l'' U2 L U L'' U'' L U L'' U l'),
        ('L shapes', '(r U R'' U) (R U'' R'' U) (R U2 r'')'),
        ('L shapes', 'r U R'' U R U'' R'' U R U2 r'''),
        ('L shapes', 'y'' r U2 R'' U'' R U R'' U'' R U'' r'''),
        ('L shapes', 'y'' r U r'' R U R'' U'' R U R'' U'' r U'' r'''),
        ('L shapes', 'y2 l U L'' U L U'' L'' U L U2 l'''),
        ('Line Shapes', 'R U2 R2 (U'' R U'' R'') U2 (F R F'')'),
        ('Line Shapes', 'y R'' F U R U'' R2 F'' R2 U R'' U'' R'),
        ('Line Shapes', 'y R'' F R U R U'' R2 F'' R2 U'' R'' U R U R'''),
        ('Line Shapes', 'R U2 R2 U'' R U'' R'' U2 F R F'''),
        ('Line Shapes', 'r U2 R2 F R F'' U2 r'' F R F'''),
        ('Line Shapes', '(r U r'') (U R U'' R'') (U R U'' R'') (r U'' r'')'),
        ('Line Shapes', 'r U r'' U R U'' R'' U R U'' R'' r U'' r'''),
        ('Line Shapes', 'r U r'' U R U'' R'' M'' U R U2 r'''),
        ('Line Shapes', 'F R U R'' U'' R F'' r U R'' U'' r'''),
        ('Line Shapes', 'r'' U'' r U'' R'' U R U'' R'' U R r'' U r'),
        ('All Corners Orientated', '(R U R'' U'') M'' (U R U'' r'')'),
        ('All Corners Orientated', 'R U R'' U'' M'' U R U'' r'''),
        ('All Corners Orientated', 'y R U'' R'' S'' R U R'' S'),
        ('All Corners Orientated', 'y R U R'' S'' R U'' R'' S'),
        ('All Corners Orientated', 'R U R'' U'' R'' r U R U'' r''')
)
INSERT INTO "Algorithms" ("Moves", "AlgorithmCaseId", "UserId")
SELECT oll_algorithms.moves, algorithm_cases."Id", NULL
FROM oll_algorithms
JOIN "AlgorithmCases" AS algorithm_cases
    ON algorithm_cases."Name" = oll_algorithms.case_name
JOIN "AlgorithmSets" AS algorithm_sets
    ON algorithm_sets."Id" = algorithm_cases."AlgorithmSetId"
   AND algorithm_sets."Name" = 'OLL'
WHERE NOT EXISTS (
    SELECT 1
    FROM "Algorithms" AS existing_algorithm
    WHERE existing_algorithm."AlgorithmCaseId" = algorithm_cases."Id"
      AND existing_algorithm."Moves" = oll_algorithms.moves
);

COMMIT;
