// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921042118_AddOllGroups")]
    partial class AddOllGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Algorithm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmCaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Moves")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmCaseId");

                    b.ToTable("Algorithms");
                });

            modelBuilder.Entity("backend.Models.AlgorithmCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlgorithmGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("AlgorithmSetId")
                        .HasColumnType("integer");

                    b.Property<int?>("CaseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmGroupId");

                    b.HasIndex("AlgorithmSetId", "CaseNumber")
                        .IsUnique();

                    b.ToTable("AlgorithmCases");
                });

            modelBuilder.Entity("backend.Models.AlgorithmGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmSetId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmSetId", "Name")
                        .IsUnique();

                    b.ToTable("AlgorithmGroups");
                });

            modelBuilder.Entity("backend.Models.AlgorithmSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlgorithmSets");
                });

            modelBuilder.Entity("backend.Models.Solve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Penalty")
                        .HasColumnType("integer");

                    b.Property<string>("Scramble")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolveTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeSolved")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Solves", null, t =>
                        {
                            t.HasCheckConstraint("CK_Solves_SolveTime_NonNegative", "\"SolveTime\" >= 0");
                        });
                });

            modelBuilder.Entity("backend.Models.Algorithm", b =>
                {
                    b.HasOne("backend.Models.AlgorithmCase", "AlgorithmCase")
                        .WithMany("Algorithms")
                        .HasForeignKey("AlgorithmCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmCase");
                });

            modelBuilder.Entity("backend.Models.AlgorithmCase", b =>
                {
                    b.HasOne("backend.Models.AlgorithmGroup", "AlgorithmGroup")
                        .WithMany("Cases")
                        .HasForeignKey("AlgorithmGroupId");

                    b.HasOne("backend.Models.AlgorithmSet", "AlgorithmSet")
                        .WithMany("Cases")
                        .HasForeignKey("AlgorithmSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmGroup");

                    b.Navigation("AlgorithmSet");
                });

            modelBuilder.Entity("backend.Models.AlgorithmGroup", b =>
                {
                    b.HasOne("backend.Models.AlgorithmSet", "AlgorithmSet")
                        .WithMany("Groups")
                        .HasForeignKey("AlgorithmSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmSet");
                });

            modelBuilder.Entity("backend.Models.AlgorithmCase", b =>
                {
                    b.Navigation("Algorithms");
                });

            modelBuilder.Entity("backend.Models.AlgorithmGroup", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("backend.Models.AlgorithmSet", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
