// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Controllers;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(SolveContext))]
    [Migration("20260902140745_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("backend.Controllers.Solve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Penalty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scramble")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SolveTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeSolved")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Solves");
                });
#pragma warning restore 612, 618
        }
    }
}
