// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923141022_AddTrainingProgressAndPreferences")]
    partial class AddTrainingProgressAndPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Algorithm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmCaseId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStandard")
                        .HasColumnType("boolean");

                    b.Property<string>("Moves")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AlgorithmCaseId" }, "IX_Algorithms_StandardPerCase")
                        .IsUnique()
                        .HasFilter("\"IsStandard\" = true");

                    b.ToTable("Algorithms");
                });

            modelBuilder.Entity("backend.Models.AlgorithmCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlgorithmGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("AlgorithmSetId")
                        .HasColumnType("integer");

                    b.Property<int?>("CaseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmGroupId");

                    b.HasIndex("AlgorithmSetId", "CaseNumber")
                        .IsUnique();

                    b.ToTable("AlgorithmCases");
                });

            modelBuilder.Entity("backend.Models.AlgorithmGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmSetId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmSetId", "Name")
                        .IsUnique();

                    b.ToTable("AlgorithmGroups");
                });

            modelBuilder.Entity("backend.Models.AlgorithmSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlgorithmSets");
                });

            modelBuilder.Entity("backend.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlgorithmSetId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WhenMade")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmSetId");

                    b.HasIndex("UserId", "AlgorithmSetId")
                        .IsUnique()
                        .HasFilter("\"Type\" = 1 AND \"AlgorithmSetId\" IS NOT NULL");

                    b.ToTable("Sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sessions_TrainingSession_AlgorithmSet", "\"Type\" <> 1 OR \"AlgorithmSetId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("backend.Models.Solve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlgorithmCaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer");

                    b.Property<string>("Scramble")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("SolveTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeSolved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmCaseId");

                    b.HasIndex("SessionId");

                    b.ToTable("Solves", null, t =>
                        {
                            t.HasCheckConstraint("CK_Solves_SolveTime_NonNegative", "\"SolveTime\" >= 0");
                        });
                });

            modelBuilder.Entity("backend.Models.TrainingPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmSetId")
                        .HasColumnType("integer");

                    b.Property<int>("Focus")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludeLearned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeLearning")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeNotLearned")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("SelectedCaseIds")
                        .HasColumnType("integer[]");

                    b.Property<int>("SlowestCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmSetId");

                    b.HasIndex("UserId", "AlgorithmSetId")
                        .IsUnique();

                    b.ToTable("TrainingPreferences");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.UserAlgorithmCaseProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmCaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmCaseId");

                    b.HasIndex("UserId", "AlgorithmCaseId")
                        .IsUnique();

                    b.ToTable("UserAlgorithmCaseProgress");
                });

            modelBuilder.Entity("backend.Models.Algorithm", b =>
                {
                    b.HasOne("backend.Models.AlgorithmCase", "AlgorithmCase")
                        .WithMany("Algorithms")
                        .HasForeignKey("AlgorithmCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmCase");
                });

            modelBuilder.Entity("backend.Models.AlgorithmCase", b =>
                {
                    b.HasOne("backend.Models.AlgorithmGroup", "AlgorithmGroup")
                        .WithMany("Cases")
                        .HasForeignKey("AlgorithmGroupId");

                    b.HasOne("backend.Models.AlgorithmSet", "AlgorithmSet")
                        .WithMany("Cases")
                        .HasForeignKey("AlgorithmSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmGroup");

                    b.Navigation("AlgorithmSet");
                });

            modelBuilder.Entity("backend.Models.AlgorithmGroup", b =>
                {
                    b.HasOne("backend.Models.AlgorithmSet", "AlgorithmSet")
                        .WithMany("Groups")
                        .HasForeignKey("AlgorithmSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmSet");
                });

            modelBuilder.Entity("backend.Models.Session", b =>
                {
                    b.HasOne("backend.Models.AlgorithmSet", "AlgorithmSet")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("AlgorithmSetId");

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Solve", b =>
                {
                    b.HasOne("backend.Models.AlgorithmCase", "AlgorithmCase")
                        .WithMany("Solves")
                        .HasForeignKey("AlgorithmCaseId");

                    b.HasOne("backend.Models.Session", "Session")
                        .WithMany("Solves")
                        .HasForeignKey("SessionId");

                    b.Navigation("AlgorithmCase");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("backend.Models.TrainingPreferences", b =>
                {
                    b.HasOne("backend.Models.AlgorithmSet", "AlgorithmSet")
                        .WithMany()
                        .HasForeignKey("AlgorithmSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.UserAlgorithmCaseProgress", b =>
                {
                    b.HasOne("backend.Models.AlgorithmCase", "AlgorithmCase")
                        .WithMany()
                        .HasForeignKey("AlgorithmCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgorithmCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.AlgorithmCase", b =>
                {
                    b.Navigation("Algorithms");

                    b.Navigation("Solves");
                });

            modelBuilder.Entity("backend.Models.AlgorithmGroup", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("backend.Models.AlgorithmSet", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Groups");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("backend.Models.Session", b =>
                {
                    b.Navigation("Solves");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
